---
title: "Quiz 2"
author: "Francisco Santamarina"
date: "November 1, 2016"
output: pdf_document
---
Load the necessary packages and dataset:
```{r}
library( dplyr ) 
library( scales ) 
setwd( "C:/Users/franc/Documents/Graduate School/PAI 730 Data-Driven Mgmt/Quiz 2" )  
dat <- read.csv( "C:/Users/franc/Documents/Graduate School/PAI 730 Data-Driven Mgmt/Quiz 2/NhoodValPerAcreByDecade.csv", stringsAsFactors=F )
#dat <- tbl_df(dat)
#nhoods <- select( .data=dat, Brighton,	CourtWoodlawn,	Meadowbrook,	Eastwood,	Elmwood,	FarWestside,	FranklinSquare,	HawleyGreen,	Lakefront,	LincolnHill,	Meadowbrook,	NearEastside,	NearWestside,	NorthValley,	Northside,	OuterComstock,	ParkAve,	ProspectHill,	SaltSprings,	Sedgwick,	SkunkCity,	SouthCampus,	SouthValley,	Southside,	Southwest,	Strathmore,	TippHill,	WashingtonSquare,	UniversityNeighborhood,	WashingtonSquare,	Westcott,	Winkworth)

numsubset <- select( .data=dat, Meadowbrook, Southwest, WashingtonSquare, Westcott)
#sums.nhoods <- colSums( nhoods, na.rm = T)
#sums.numsubset <- colSums( numsubset, na.rm = T)
#max.nhood <- which.max(sums.nhoods)
#max.nhood
#max.numsubset <- which.max(sums.numsubset)
#max.numsubset
#min.nhood <- which.min(sums.nhoods)
#min.nhood
#min.numsubset <- which.min(sums.numsubset)
#min.numsubset

subset <- select( .data=dat, decade, year,  Meadowbrook, Southwest, WashingtonSquare, Westcott)
```

```{r}
#Setting global variables
minyr <- min( subset$year )
minyr
minx <- minyr - 10
maxyr <- max( subset$year )
maxyr
maxx <- maxyr + 10
minamount <- min(numsubset, na.rm=T)
minamount
miny <- 17000
maxamount <- max(numsubset, na.rm=T)
maxamount
maxy <- 880000
```

```{r}
par( mfrow = c( 2,2 ) )



####Plot for Meadowbrook
nhd <- "Meadowbrook"
plot( x=subset$year,
      xlim=c( minx, maxx),
      ylim=c( minamount, maxamount),
      main=nhd, 
      yaxt='n',
      xaxt='n',
      xlab="",
      ylab="",
      bty="n" #gets rid of the box around the plot
)
points( seq(minyr, maxyr, 10), subset[,"Meadowbrook"], type="l", lwd=2 )  # Meadowbrook
points( seq(minyr, maxyr, 10), subset[,"Southwest"], type="l", lwd=2 )  # Southwest
points( seq(minyr, maxyr, 10), subset[,"WashingtonSquare"], type="l", lwd=2 )  # WashingtonSquare
points( seq(minyr, maxyr, 10), subset[,"Westcott"], type="l", lwd=2 )  # Westcott

points( seq(minyr, maxyr, 10), subset[,nhd], type="l", lwd=3, col="royalblue4" )
points( minyr, subset[1,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
points( 2005, subset[11,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
text( minyr, subset[1,nhd], dollar( subset[1,nhd] ), pos=2, srt=90 )
text( maxyr, subset[11,nhd], dollar( subset[11,nhd] ), srt=90 )



####Plot for Southwest
nhd <- "Southwest"
plot( x=subset$year,
      xlim=c( minx, maxx),
      ylim=c( minamount, maxamount),
      main=nhd, 
      yaxt='n',
      xaxt='n',
      xlab="",
      ylab="",
      bty="n" #gets rid of the box around the plot
)
points( seq(minyr, maxyr, 10), subset[,"Meadowbrook"], type="l", lwd=2 )  # Meadowbrook
points( seq(minyr, maxyr, 10), subset[,"Southwest"], type="l", lwd=2 )  # Southwest
points( seq(minyr, maxyr, 10), subset[,"WashingtonSquare"], type="l", lwd=2 )  # WashingtonSquare
points( seq(minyr, maxyr, 10), subset[,"Westcott"], type="l", lwd=2 )  # Westcott

points( seq(minyr, maxyr, 10), subset[,nhd], type="l", lwd=3, col="royalblue4" )
points( minyr, subset[1,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
points( maxyr, subset[12,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
text( minyr, subset[1,nhd], dollar( subset[1,nhd] ), pos=4, srt=90 )
text( maxyr, subset[12,nhd], dollar( subset[12,nhd] ), pos=3, srt=90 )


####Plot for WashingtonSquare
nhd <- "WashingtonSquare"
plot( x=subset$year,
      xlim=c( minx, maxx),
      ylim=c( minamount, maxamount),
      main=nhd, 
      yaxt='n',
      xlab="",
      ylab="",
      bty="n" #gets rid of the box around the plot
)
points( seq(minyr, maxyr, 10), subset[,"Meadowbrook"], type="l", lwd=2 )  # Meadowbrook
points( seq(minyr, maxyr, 10), subset[,"Southwest"], type="l", lwd=2 )  # Southwest
points( seq(minyr, maxyr, 10), subset[,"WashingtonSquare"], type="l", lwd=2 )  # WashingtonSquare
points( seq(minyr, maxyr, 10), subset[,"Westcott"], type="l", lwd=2 )  # Westcott

points( seq(minyr, maxyr, 10), subset[,nhd], type="l", lwd=3, col="royalblue4" )
points( minyr, subset[1,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
points( maxyr, subset[12,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
text( minyr, subset[1,nhd], dollar( subset[1,nhd] ), srt=90 )
text( maxyr, subset[12,nhd], dollar( subset[12,nhd] ), pos = 1, srt=90 )


####Plot for Westcott
nhd <- "Westcott"
plot( x=subset$year,
      xlim=c( minx, maxx),
      ylim=c( minamount, maxamount),
      main=nhd, 
      yaxt='n',
      xlab="",
      ylab="",
      bty="n" #gets rid of the box around the plot
)
points( seq(minyr, maxyr, 10), subset[,"Meadowbrook"], type="l", lwd=2 )  # Meadowbrook
points( seq(minyr, maxyr, 10), subset[,"Southwest"], type="l", lwd=2 )  # Southwest
points( seq(minyr, maxyr, 10), subset[,"WashingtonSquare"], type="l", lwd=2 )  # WashingtonSquare
points( seq(minyr, maxyr, 10), subset[,"Westcott"], type="l", lwd=2 )  # Westcott

points( seq(minyr, maxyr, 10), subset[,nhd], type="l", lwd=3, col="royalblue4" )
points( minyr, subset[1,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
points( maxyr, subset[12,nhd], type="p", pch=16, cex=1.1, col="royalblue4" )
text( minyr, subset[1,nhd], dollar( subset[1,nhd] ), srt=90 )
text( maxyr, subset[12,nhd], dollar( subset[12,nhd] ), srt=90 )
```

